# Date : 2023-1-1
# 全寿命计划过修参数
# 季度
over_repair_restrictions_on_turnover: 2
# 百分比
over_repair_restrictions_on_not_turnover: 0.1








file_path : ./datasets
WorkPackageFilename : WorkPackageData.xlsx
TrainDataFilename : TrainData.xlsx
LastMaintenTimeFilename : LastMaintenTime.xlsx
today : 2023-4-1
NumberOfMaintenTrainsPerDay: 3
SpecialWorkPackage : 1601-01 1602-01 1603-01 1801-01 1802-01 1803-01 1804-01
seed : 1